### ISSUE TITLE
[Visual]: Request to fix vanilla bug

### ISSUE THREAD

**Issue by DarianLStephens** [FalsePattern/Triangulator#9] opened 2022-03-15 06:23 UTC
### OS

Windows

### GPU

NVIDIA

### Game log

I don't think the log will help, considering it's a vanilla bug.

### Description

Very hard lines between various bits of lighting along edges, especially noticeable in a white box.
![2022-03-15_17 20 01](https://user-images.githubusercontent.com/15375876/158319030-9a7ad491-c2f9-4dd5-a95e-19aaea43aaa3.png)
Close look to make it easier to see:
![2022-03-15_17 23 38](https://user-images.githubusercontent.com/15375876/158319267-3846c681-f444-46f4-ba4f-9625743d2218.png)

It's only really noticeable in the dark, possibly entirely gone if in direct sunlight.
![2022-03-15_17 24 24](https://user-images.githubusercontent.com/15375876/158319330-3db23676-343e-4aeb-a376-ccbe5dae7444.png)
It IS still visible at night, though.
![2022-03-15_17 24 21](https://user-images.githubusercontent.com/15375876/158319353-81712b71-c82a-4502-a8f8-6e0d41b7fe66.png)

The bug is described in more detail, along with code examples and a fix, in this Mojang bug report:
https://bugs.mojang.com/browse/MC-43968

I know this isn't a bug with Triangulator, but I'm hoping it's something the mod might be able to fix given its fix of ambient occlusion.

**Comment by DarianLStephens** [comment] 2022-03-15 06:31
I don't know if this is related, but AO seems to have weird lines going through it, and a very abrupt end.
![2022-03-15_17 30 15](https://user-images.githubusercontent.com/15375876/158320183-b1d7f8ea-2c90-4e08-a7e0-491fa227558f.png)

I feel like it's meant to fade to 0 from the start, not seemingly half-way through.

**Comment by FalsePattern** [comment] 2022-03-27 17:07
So i've looked into this rendering issue a bit further, it looks like an issue with how vanilla minecraft calculates the combination of AO and changing light levels.

Currently, i have absolutely no idea how this could be fixed without rewriting the entire AO calculation logic of Minecraft (about 1200 lines of code)

**Comment by embeddedt** [comment] 2022-05-12 02:07
@FalsePattern Here's a fix I made for my private bugfix mod for [MC-43968](https://bugs.mojang.com/browse/MC-43968), not sure if it will fix this issue or not but you're welcome to use it/incorporate it if you'd like: https://gist.github.com/embeddedt/19e2c103841fac23145b0cf125268f73

It's essentially the fix described in the bug report but implemented using (very fragile) mixins instead.

**Comment by FalsePattern** [comment] 2022-06-01 18:31
> @FalsePattern Here's a fix I made for my private bugfix mod for [MC-43968](https://bugs.mojang.com/browse/MC-43968), not sure if it will fix this issue or not but you're welcome to use it/incorporate it if you'd like: https://gist.github.com/embeddedt/19e2c103841fac23145b0cf125268f73
> 
> It's essentially the fix described in the bug report but implemented using (very fragile) mixins instead.

so i've added your patch to triangulator, and all i can say is: *wow*
without your patch:
![2022-06-01_17 08 17](https://user-images.githubusercontent.com/30945458/171476795-2f823122-fa7d-4e3a-9b92-59d0b4b535a9.png)

with your patch:
![2022-06-01_17 08 41](https://user-images.githubusercontent.com/30945458/171476812-782e4d3d-4b82-4986-ba82-ec7daf1ebf30.png)

**Comment by DarianLStephens** [comment] 2022-06-02 07:21
YEAH!
I've wanted to see this thing fixed for literal years, and seeing it finally done is so awesome!

**Comment by DarianLStephens** [comment] 2022-06-02 07:22
I am quite curious about that 'private bugfix mod', though. I wonder what else is in there?

**Comment by DarianLStephens** [comment] 2022-06-03 16:35
While that specific staircase instance seems to be fixed, it unfortunately didn't help with the white wall.
![2022-06-04_02 34 59](https://user-images.githubusercontent.com/15375876/171907839-cfb685f1-91e0-492f-a54e-9d71ed5a8893.png)
![2022-06-04_02 35 10](https://user-images.githubusercontent.com/15375876/171907853-0ad3713e-d3a0-408c-9c81-6c76bfbb2a57.png)

**Comment by FalsePattern** [comment] 2022-06-03 16:53
so i did some more digging, apparently the staircase and the wall bugs are completely separate.
the staircase glitch was caused by the AO code, while the blocky light is caused by the brightness smoothing code

The main difference is that in the AO bug, it was caused by an actual programming error, while it looks like the reason for the non-perfect smooth lighting is the fact that it uses `int`s instead of `float`s while calculating the per-vertex brightness (for who knows what reason)

I'll try reusing the stuff i learned from embeddedt's AO fix code and attempt to fix this limitation

**Comment by FalsePattern** [comment] 2022-06-03 17:04
![image](https://user-images.githubusercontent.com/30945458/171912020-110940bb-204e-432a-b318-c5b0c8ccc825.png)
i temporarily disabled AO with some test code to see smooth lighting without the AO adding noise, and yep, it's a smooth lighting bug 100%

**Comment by FalsePattern** [comment] 2022-06-03 18:12
update:
![image](https://user-images.githubusercontent.com/30945458/171922136-4e4617d0-130a-471d-88c4-325b69a0aff0.png)
![image](https://user-images.githubusercontent.com/30945458/171922191-712dd0c1-de4c-4a5f-9c5e-821ec3fe68c9.png)
![image](https://user-images.githubusercontent.com/30945458/171922219-2854eaeb-0184-4312-9618-6934e0c3f7f6.png)
:eyes:

**Comment by DarianLStephens** [comment] 2022-06-03 18:35
That's definitely _way_ better, but I wonder if there's anything you can do about the strange lines?
It's like the brightness isn't being done properly, even if it's smoothed now.

**Comment by DarianLStephens** [comment] 2022-06-03 18:44
I just wanted to see how far back these issues ran, and...
![2022-06-04_04 42 42](https://user-images.githubusercontent.com/15375876/171926999-eaadf85f-e8c7-4ff5-908d-48af0441c950.png)
I did _not_ think they were present all the way back here!

I'll need to do a bit of survival to test it in earlier versions, but I could have sworn there was a point where it was okay, maybe even closer to the initial implementation of the Smooth Lighting mod?

**Comment by DarianLStephens** [comment] 2022-06-03 19:03
Okay, so, Beta 1.7.3 seemed okay.
![2022-06-04_05 01 34](https://user-images.githubusercontent.com/15375876/171931222-80111104-fa33-4747-8706-0eac8466350a.png)

However, even that suffered from the directional AO problem! I never noticed it back then!
![2022-06-04_05 01 46](https://user-images.githubusercontent.com/15375876/171931265-fa12f8cb-3499-4228-be17-839fb2e134f4.png)
I guess it's just one of those things that's always been there, and you can't unsee once you notice it, huh?

**Comment by DarianLStephens** [comment] 2022-06-03 21:42
Is it possible to disable that interpolation you mentioned, or is it a consequence of how GPUs work?

**Comment by FalsePattern** [comment] 2022-06-03 21:45
it's a fixed behaviour of GPUs, where data between the vertices of a triangle get interpolated linearly. This is how you can have textures, for instance, because the x/y coordinates of the texture gets interpolated across the whole triangle.

**Closed** 2022-06-04 17:00 UTC
Labels: enhancement, visual

**Comment by embeddedt** [comment] 2022-06-04 18:30
> I am quite curious about that 'private bugfix mod', though. I wonder what else is in there?

I have a lot of miscellaneous bugfixes for issues I'm encountering while playing 1.7. The main reason I've kept it private is because they are very untested and some of them might even be questionable. I also sometimes add experimental fixes that end up causing glitches in the world that are hard to revert (e.g. partially ungenerated structures), and I wouldn't want users' worlds to be corrupted by bugs I introduce. 1.7 is also even less popular than 1.12, itself a largely abandoned version.

Also, I cannot take credit for all of these fixes; some of them (including the AO fix) are based on the many pointers TheMasterCaver has left in his various forum posts and/or code analyses in Mojira bug reports.

**Comment by DarianLStephens** [comment] 2022-06-07 21:14
Hey, sorry to bring this up again, but it seems that some non-full blocks have weird AO or smooth lighting, as well.
![2022-06-08_06 22 34](https://user-images.githubusercontent.com/15375876/172483066-d4d52de7-9e72-4d43-bc37-8e91af020973.png)

Farmland is a vanilla example:
![2022-06-08_07 13 34](https://user-images.githubusercontent.com/15375876/172483781-9ed5e338-3979-4d26-86e2-ea85bebb29fc.png)
![2022-06-08_07 13 36](https://user-images.githubusercontent.com/15375876/172483786-ef8331fe-326c-4e79-bf9c-b797127e379d.png)

Another problem is present underwater, too:
![2022-06-08_07 14 34](https://user-images.githubusercontent.com/15375876/172483913-a9410007-c6d4-4155-bcbb-256b87a54b7f.png)

**Comment by FalsePattern** [comment] 2022-06-07 21:43
The underwater bug is caused by the faster fall-off of lights, while the smooth lighting logic is coded for 1 light level per block falloff, can't really do anything about that

As for the non-full block rendering, it's implemented in completely different parts of the code i haven't read yet.

I might look into these in the future, but triangulator is low priority for the time being, i need to focus on some private projects for a few weeks

**Comment by DarianLStephens** [comment] 2022-06-09 20:51
I know you're not back yet, but I want to document this in case it helps once you are.
I've discovered something rather interesting about the non-full-block AO.

This is with Triangulator installed:
![2022-06-10_06 45 18](https://user-images.githubusercontent.com/15375876/172942079-d7d2ec30-5da4-4302-9168-2e27fdb1dd9b.png)

And this is after removing Triangulator:
![2022-06-10_06 49 43](https://user-images.githubusercontent.com/15375876/172942103-f7f1f019-9d70-4c19-ac8f-5977f4d7088c.png)

**Comment by DarianLStephens** [comment] 2022-06-09 20:59
Also, a much better example of the directional bias in smooth lighting, and which you corrected (For the most part) in AO with your predictive triangle switching stuff:
![2022-06-10_06 58 58](https://user-images.githubusercontent.com/15375876/172943369-c1705923-a766-4cbc-834b-2daae8735573.png)
