### ISSUE TITLE
[Compatibility Request]: ChromatiCraft Runes

### ISSUE THREAD

**Issue by Asveste** [FalsePattern/Triangulator#19] opened 2022-06-15 02:23 UTC
### Other mod's name

ChromatiCraft

### Other mod's homepage

https://reikakalseki.github.io/minecraft/mods/chromaticraft.html

### Other mod's license

All Rights Reserved

### Game log

[Uploading fml-client-latest.log…]()

### Description

The runes from ChromatiCraft have some visual glitches when the player moves around.

Since a screenshot is kind of hard to do I attached a video

https://user-images.githubusercontent.com/23436647/173723000-2aa0d4bc-902c-4725-924f-e9c242680411.mp4

### Existing Patches

- [X] This request is not for OptiFine
- [X] This request is not for FoamFix
- [X] This request is not for RedstonePaste

**Comment by FalsePattern** [comment] 2022-06-25 17:35
I could not reproduce this bug, it's most likely a driver issue.

**Comment by FalsePattern** [comment] 2022-06-25 19:17
fixed in 1.6.2

**Closed by FalsePattern** 2022-06-25 19:17 UTC
Labels: compat-request
